openapi: 3.0.0
info:
  title: Bulk Operations Configurations
  version: v1

servers:
  - url: /bulk-operations/

paths:
  /stub:
    get:
      responses:
        "200":
          description: stub

components:
  schemas:
    job:
      $ref: '../../../../folio-export-common/schemas/job.json#/Job'
